# reconcile-views-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: scd4-psp-reconcile-views-job
  namespace: ds-scale
spec:
  template:
    spec:
      containers:
      - name: reconcile-views-handler
        image: registry.gitlab.com/datasurface-inc/datasurface/datasurface:v1.4.47
        command: ["/bin/bash"]
        args:
        - -c
        - |
          echo "Starting DataSurface reconcile views handler"

          python -m datasurface.platforms.yellow.reconcile_workspace_views \
            --psp SCD4_PSP \
            --git-repo-path /cache/git-cache \
            --git-repo-type github \
            --git-repo-url https://github.com \
            --git-repo-owner billynewport \
            --git-repo-name demo_azure_model \
            --git-repo-branch main \
            --git-platform-repo-credential-name git \
            --rte-name demo \
            
            --use-git-cache \
            
            --max-cache-age-minutes 5

          echo "Reconcile views job complete"
        env:
        - name: PYTHONPATH
          value: "/app/src"

        - name: git_TYPE
          value: "API_TOKEN"

        - name: git_TOKEN
          valueFrom:
            secretKeyRef:
              name: git
              key: TOKEN


        - name: sqlserver-demo-merge_TYPE
          value: "USER_PASSWORD"

        - name: sqlserver-demo-merge_USER
          valueFrom:
            secretKeyRef:
              name: sqlserver-demo-merge
              key: USER
        - name: sqlserver-demo-merge_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-demo-merge
              key: PASSWORD


        - name: azure-bulk-writer_TYPE
          value: "USER_PASSWORD"

        - name: azure-bulk-writer_USER
          valueFrom:
            secretKeyRef:
              name: azure-bulk-writer
              key: USER
        - name: azure-bulk-writer_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azure-bulk-writer
              key: PASSWORD


        - name: sqlserver-cqrs_TYPE
          value: "USER_PASSWORD"

        - name: sqlserver-cqrs_USER
          valueFrom:
            secretKeyRef:
              name: sqlserver-cqrs
              key: USER
        - name: sqlserver-cqrs_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-cqrs
              key: PASSWORD



        volumeMounts:
        - name: git-model-cache
          mountPath: /cache/git-cache
      volumes:
      - name: git-model-cache
        persistentVolumeClaim:
          claimName: git-cache-pvc

      restartPolicy: Never
  backoffLimit: 3